server:
  port: 9997
---
#logging:
#  level:
#    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
---
spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
#    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          order_inserts: true
        generate_statistics: false
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: pwd
    driver-class-name: org.h2.Driver
#  datasource:
#    url: jdbc:mariadb://localhost:3306/test_db
#    username: sa
#    password: pwd
#    driver-class-name: org.mariadb.jdbc.Driver
  batch:
    job:
      enabled: false
  kafka:
    bootstrap-servers: localhost:9092