version: "2.1"
services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
#    volumes:
#      - 'zookeeper_data:/bitnami'
    environment:
      ZOO_ENABLE_AUTH: "yes"
      ZOO_SERVER_USERS: "sasl_user"
      ZOO_SERVER_PASSWORDS: "sasl_user_password"

      ZOO_LOG_LEVEL: "DEBUG"
#       We set “ALLOW_ANONYMOUS_LOGIN” configuration to true because we want to allow users to connect to ZooKeeper easily (without authentication), this configuration is not suitable for production use.
#      ALLOW_ANONYMOUS_LOGIN: "yes"
  kafka:
    image: 'docker.io/bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: "CLIENT://localhost:9092,INTERNAL://kafka:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "CLIENT://localhost:9092,INTERNAL://kafka:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CLIENT:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT"

      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
#      Set either KAFKA_INTER_BROKER_LISTENER_NAME or KAFKA_SECURITY_INTER_BROKER_PROTOCOL; not both
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
#      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: "SASL_PLAINTEXT"
#      ALLOW_PLAINTEXT_LISTENER: "yes"

      KAFKA_CFG_SASL_ENABLED_MECHANISMS: "SCRAM-SHA-512"
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "SCRAM-SHA-512"
#      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
#      KAFKA_SUPER_USERS: "User:admin"
#      KAFKA_ZOOKEEPER_SET_ACL: "true"

      KAFKA_INTER_BROKER_USER: "admin"
      KAFKA_INTER_BROKER_PASSWORD: "admin-secret"

#     In order for KAFKA Clients to connect to Kafka Brokers
      KAFKA_CLIENT_USERS: "user"
      KAFKA_CLIENT_PASSWORDS: "password"

#     In order to authenticate Kafka against a Zookeeper server with SASL, you should provide the environment variables below:
      KAFKA_ZOOKEEPER_PROTOCOL: SASL
      KAFKA_ZOOKEEPER_USER: "sasl_user"
      KAFKA_ZOOKEEPER_PASSWORD: "sasl_user_password"

#      KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/bitnami/kafka/config/kafka_server_jaas.conf"

    depends_on:
      - zookeeper
#    volumes:
#      - type: "bind"
#        source: "/System/Volumes/Data/Users/guozheng/.kafka_docker/kafka_jaas_server"
#        target:  "/opt/bitnami/kafka/config"
