version: "2.1"
networks:
  myNetwork:
    name: myNetwork
services:
  zookeeper:
#    image: 'bitnami/zookeeper:3.7.0-debian-10-r96'
    image: 'bitnami/zookeeper:3.7.0-debian-10-r96'
    ports:
      - '2181:2181'
    networks:
      - myNetwork
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
  kafka:
#    image: 'bitnami/kafka:2.8.0-debian-10-r55'
    image: 'bitnami/kafka:2.8.0-debian-10-r55'
    ports:
      - '9092:9092'
    networks:
      - myNetwork
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_CFG_ADVERTISED_PORT: "9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1 #If you have set the TransactionalId in the ProducerConfig, then you need to make sure this factor value is the same as the number of brokers you spin up. Default is 3.
    depends_on:
      - zookeeper