spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:3000:ORCLCDB
    username: app_user
    password: pwd
    driver-class-name: oracle.jdbc.OracleDriver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
server:
  port: 9997
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: src/main/resources/client.keystore.jks
    key-store-password: password1234
    key-alias: localhost
    trust-store: src/main/resources/client.truststore.jks
    trust-store-password: password1234