spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:3000:ORCLCDB
    username: app_user
    password: pwd
    driver-class-name: oracle.jdbc.OracleDriver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
