apiVersion: v1
kind: Namespace
metadata:
  name: appspace
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: appspace
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - name: kafka-port
      port: 9092
      targetPort: kafka-port
      protocol: TCP
    - name: zookeeper-port
      port: 2181
      targetPort: zookeeper-port
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: appspace
  labels:
    app: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - name: zookeeper-port
      port: 2181
      targetPort: 2181
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  namespace: appspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
      name: zookeeper
  template:
    metadata:
      name: zookeeper-pod
      labels:
        name: zookeeper
        app: zookeeper
    spec:
      hostname: zookeeper
      containers:
        - name: zookeeper
          image: docker.io/bitnami/zookeeper:3-debian-10
          imagePullPolicy: Always
          ports:
            - name: zookeeper-port
              containerPort: 2181
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: appspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      name: kafka
  template:
    metadata:
      name: kafka-pod
      labels:
        app: kafka
        name: kafka
    spec:
      hostname: kafka
      containers:
        - name: kafka
          image: docker.io/bitnami/kafka:2-debian-10
          imagePullPolicy: Always
          ports:
            - name: kafka-port
              containerPort: 9092
            - name: zookeeper-port
              containerPort: 2181
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
            - name: KAFKA_CFG_ADVERTISED_HOST_NAME
              value: "kafka"
            - name: KAFKA_CFG_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"